### ISSUE TITLE
friendlier fail `astro airflow start` 

### ISSUE THREAD

**Issue by ryw** [astronomerio/astro-cli#6] opened 2018-02-16 20:42 UTC
* Prevent from starting if port is allocated
* Better error messages on failure

**Comment by andscoop** [comment] 2018-04-14 15:49
@schnie I agree with the high-level objective here, but I think the issue we were seeing here was the result of it being a development machine. I have not run into this error since. How do you feel about closing this and opening other tickets for when we are able to capture a reproducible bug?

**Comment by schnie** [comment] 2018-04-14 16:28
@andscoop what happens if you run `astro airflow start` in two different project directories? I would think there would be some port conflicts when starting a second.

**Comment by benjamingregory** [comment] 2018-06-07 21:39
Related to this -- if you issue `astro airflow start` before an `astro airflow init`, you get the following error. 

```
MacBook-Pro-6:calibermind-pipelines tardis5$ astro airflow start
invalid argument "/airflow:latest" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
panic: exit status 125

goroutine 1 [running]:
github.com/astronomerio/astro-cli/docker.Exec(0xc4204cdbc0, 0x4, 0x4)
	/go/src/github.com/astronomerio/astro-cli/docker/docker.go:27 +0x13f
github.com/astronomerio/astro-cli/airflow.imageBuild(0xc420251c20, 0x3f, 0xc420236240, 0xf)
	/go/src/github.com/astronomerio/astro-cli/airflow/docker.go:62 +0x92
github.com/astronomerio/astro-cli/airflow.Start(0xc420251c20, 0x3f, 0x0, 0x0)
	/go/src/github.com/astronomerio/astro-cli/airflow/docker.go:151 +0x4db
github.com/astronomerio/astro-cli/cmd.airflowStart(0x19fc240, 0x1a29fb0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/astronomerio/astro-cli/cmd/airflow.go:193 +0x39
github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra.(*Command).execute(0x19fc240, 0x1a29fb0, 0x0, 0x0, 0x19fc240, 0x1a29fb0)
	/go/src/github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra/command.go:698 +0x47b
github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x19fe220, 0x1, 0x0, 0x0)
	/go/src/github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra/command.go:783 +0x349
github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x19fe220, 0xc420000340, 0xc420000340)
	/go/src/github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/go/src/github.com/astronomerio/astro-cli/main.go:10 +0x2d
```

**Comment by andscoop** [comment] 2018-06-14 18:10
@benjamingregory I am not able to replicate that particular failure

Steps I took

1.) `mkdir test && cd test`
2.) `astro airflow start`

response: `Error: Not in an astronomer project directory`

Do you have anymore insight?

**Comment by benjamingregory** [comment] 2018-06-14 18:31
I just replicated. It looks like that error occurs when you try to `astro airflow start` where .astro exists but the `.astro/config.yaml` does not. 

A rare occurrence admittedly but thats the error that corresponds to it.

**Closed** 2018-08-22 18:26 UTC
Labels: 4: Milestone Focus
