### ISSUE TITLE
Error when trying to pip install new version of existing package

### ISSUE THREAD

**Issue by benjamingregory** [astronomerio/astro-cli#118] opened 2018-09-13 18:00 UTC
I tried adding `pandas==0.23.0` requirements.txt and received the following error on build. When I exec'd into the container, pandas v0.22.0 was present. 

CLI version: 0.2.3

@andscoop was able to replicate on the most recent version 

```
MacBook-Pro-6:2.1_task_creation tardis5$ astro airflow start
Sending build context to Docker daemon  8.192kB
Step 1/1 : FROM astronomerinc/ap-airflow:latest-onbuild
# Executing 3 build triggers
 ---> Running in 4350cfe1fb4f
OK: 92 MiB in 37 packages
Removing intermediate container 4350cfe1fb4f
 ---> Running in d57ab17109a3
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0g7w8dk4/pandas/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-y90wy1gf-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-0g7w8dk4/pandas/
The command '/bin/sh -c pip install --no-cache-dir -q -r requirements.txt' returned a non-zero code: 1
panic: exit status 1

goroutine 1 [running]:
github.com/astronomerio/astro-cli/docker.Exec(0xc4204d1bd0, 0x4, 0x4)
    /go/src/github.com/astronomerio/astro-cli/docker/docker.go:27 +0x13f
github.com/astronomerio/astro-cli/airflow.imageBuild(0xc4200140a4, 0x49, 0xc4202686a0, 0x20)
    /go/src/github.com/astronomerio/astro-cli/airflow/docker.go:68 +0x92
github.com/astronomerio/astro-cli/airflow.Start(0xc4200140a4, 0x49, 0x0, 0x0)
    /go/src/github.com/astronomerio/astro-cli/airflow/docker.go:158 +0x4eb
github.com/astronomerio/astro-cli/cmd.airflowStart(0x1a0d440, 0x1a3cb98, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/astronomerio/astro-cli/cmd/airflow.go:174 +0x39
github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra.(*Command).execute(0x1a0d440, 0x1a3cb98, 0x0, 0x0, 0x1a0d440, 0x1a3cb98)
    /go/src/github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra/command.go:698 +0x47b
github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1a0fa80, 0x1a10960, 0x0, 0x0)
    /go/src/github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra/command.go:783 +0x349
github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x1a0fa80, 0xc420000340, 0xc420000340)
    /go/src/github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
    /go/src/github.com/astronomerio/astro-cli/main.go:10 +0x2d
```

**Comment by schnie** [comment] 2018-09-13 18:02
I think pandas (guessing v0.22.0) is installed with airflow. Is it mad about that?

**Comment by benjamingregory** [comment] 2018-09-13 18:18
@schnie -- it is but theoretically this should uninstall v0.22.0 and install v0.23.0.

**Comment by schnie** [comment] 2018-09-13 18:59
I haven't tried it but I'm thinking that pip will fail one way or another if you try to pip install a new version of a package that is already installed. Isn't that what the `--upgrade` flag is for?

**Comment by andscoop** [comment] 2018-09-14 16:49
@benjamingregory Looks like this is caused by a cached tag on your system. We will be resolving this with the next release but in the meantime you can delete your `astronomerinc/ap-airflow:latest-onbuild` image and it should pull down the "latest" `latest` ;)

**Comment by benjamingregory** [comment] 2018-09-14 17:09
@andscoop If it was a local setting, then how were you able to recreate it?

**Comment by andscoop** [comment] 2018-09-15 00:29
We both likely had stale `astronomerinc/ap-airflow:latest-onbuild` on our images. Did deleting and re-pulling resolve for you?

**Closed** 2018-09-18 15:55 UTC
Labels: 1: Support/Bug
